blank_issues_enabled: false
contact_links:
  - name: A certain website is still unreachable
    url: https://github.com/SelmanBuilds/GoodByeDPI-Plus/discussions
    about: This is likely a DPI configuration issue, not a software bug. Please use Discussions for help.
  - name: Questions about the program
    url: https://github.com/SelmanBuilds/GoodByeDPI-Plus/discussions
    about: Please ask and answer questions in Discussions.
