name: Feature request
description: Suggest an idea or feature for this project

body:
  - type: markdown
    attributes:
      value: |
        If you have an idea for a new feature or bypass method that is missing
        from the project, suggest it here. But first, search existing tickets
        to make sure it hasn't been requested already.
  - type: checkboxes
    id: ensure
    attributes:
      label: I've made sure there's no existing feature request
      options:
        - label: I have searched existing issues and this feature has not been requested.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe your feature request
    validations:
      required: true
